name: dailydash
description: An integrated health management app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  http: ^1.2.2
  flutter_lints: ^4.0.0
  google_sign_in: ^6.2.1
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.4.4
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  permission_handler: ^11.3.1
  firebase_core_web: ^2.18.1
  url_launcher: ^6.0.17
  table_calendar: ^3.0.7
  firebase_ui_auth: any
  firebase_ui_oauth_google: any
  device_info_plus: ^10.1.2
  flutter_local_notifications: ^17.2.4
  intl: ^0.19.0
  uuid: ^3.0.7
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.3.2
flutter:
  uses-material-design: true
  assets:

    - assets/icons/



# Add flutter_launcher_icons configuration at root level
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"